version: "3.4"
services:
  # this is the custom build app which contains our automation test scripts
  e2e:
    image: mocha/volvo
    command: npm run wdio
    networks:
      - selenoid
    volumes:
      - "../allure-results:/usr/lib/wdio/allure-results" # volume mapping the allure results

networks:
  selenoid:
    external: true
